### ISSUE TITLE
Remove the authentification required prompt

### ISSUE THREAD

**Issue by Sakyce** [NyarchLinux/NyarchLinux#28]
Read the title, self explainative.

The default password seems to be "live".

![image](https://github.com/NyarchLinux/NyarchLinux/assets/55030860/a45b5aef-4a8e-4cf6-a5a6-ab1ea03ad264)

**Comment by FrancescoCaracciolo** [comment]
Basically I don't know how to remove it 👉👈

**Comment by Sakyce** [comment]
Lets pray for a contributor to come here :(

**Comment by FrancescoCaracciolo** [comment]
For those who want to look for the issue

Here is the script that calls calamares on startup 
https://raw.githubusercontent.com/NyarchLinux/NyarchLinux/main/Gnome/usr/share/ezarcher/Scripts/autostart.sh
Basically it's about not making pkexec ask password for the live user (or giving live as password)
It should also be done so that if .desktop file is launched, it also does not require the password.
Probably removing password request on the sudoers file for live user might help

**Comment by Magi3r** [comment]
It seems you can allow this application for pkexec in `/usr/share/polkit-1/actions/com.github.calamares.calamares.policy`, and change the lines:
```xml
<allow_any>no</allow_any>
<allow_inactive>no</allow_inactive>
<allow_active>auth_admin</allow_active>```
to 
```xml
<allow_any>no</allow_any>
<allow_inactive>no</allow_inactive>
<allow_active>yes</allow_active>```

I found this solution [here](https://askubuntu.com/questions/383747/how-to-configure-pkexec-to-not-ask-for-password).

**Comment by FrancescoCaracciolo** [comment]
Thank you, I will try it

**Comment by Magi3r** [comment]
I tried already and it works (on my machine ™️ ). But i am not sure where i have to put that file in this repo to appear at the right place when booting from the iso. I assume I would have to recreate the folder structure in the Gnome folder?

**Comment by FrancescoCaracciolo** [comment]
Yes that's right, you probably have to put it in
Gnome/usr/share/polkit-1/actions/com.github.calamares.calamares.policy

**Comment by FrancescoCaracciolo** [comment]
I also removed password request to use sudo for live user, this is finally solved
